### ISSUE TITLE
Первая итерация по скрипту

### ISSUE THREAD

**Issue by inner-whisper** [inner-whisper/nmax#1]
- [x] "Make CI green again"
- [x] #2 - Добавить rubocop
- [x] #3 - Написать интеграционный спек на выполнение `cat sample_data_40GB.txt | nmax 10000`
- [x] #4 - Реализовать чтение текстовых данных из файла (нагенерить development-пример?)
- [x] #5 Сделать вывод N самых больших целых чисел из текстовых данных
- [x] #6 Оптимизация для чтения объемного текстового потока 
- [x] Прогнать через https://gemcheck.evilmartians.io/
- [x] #8 Добавить к travis CI прогон на JRuby ~~и Rubinius~~
- [x] Причесать README по примерам из https://github.com/matiassingers/awesome-readme
- [x] Добавить https://github.com/rubocop-hq/rubocop-md к CI
- [x] Добавить Changelog (https://keepachangelog.com + https://github.com/skywinder/gitlab-changelog-generator + https://github.com/egoist/loglive)
- [x] Интегрировать отслеживание зависимостей - https://dependabot.com/
- [x] Добавить git-тэг версии `0.1.0` + проверить ссылки в Changelog-е
- [x] Пробежаться по книге Command-Line Applications in Ruby
- [x] #13 Добавить документации для YARD
